title: AzureLife Tech Blog
email: your-email@example.com
description: >-
  AzureLife의 기술, 개발, 자동화에 대한 생각과 경험을 공유하는 블로그입니다.
baseurl: ""
url: "https://azurelife.github.io"
twitter_username: azurelife
github_username:  azurelife

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
